### ISSUE TITLE
Descriptions with more than 211 characters won't display when scrolling left.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-rss#103]
**What's happening?**
When an RSS widget is configured to scroll left and showing either full description or a description snippet of more than 211, stories with more than 211 characters will not display at all.

**What should be happening?**
When an RSS widget is configured to scroll left and show a full description, stories of any size should display.

**How to recreate**
1. Add a Presentation with an RSS Widget placeholder
2. Set the presentation to the Scroll transition in the left direction
3. Add an RSS feed where most of the stories contain a lot of characters (https://www.nasa.gov/rss/dyn/breaking_news.rss)
4. Select show full description, or show description snippet and input 212 characters.

**Additional information**
Community thread: https://community.risevision.com/rise_vision_inc/topics/rss-not-loading-properly
Presentation prepared: http://preview.risevision.com/?type=presentation&id=19fc763c-5ffa-48e5-aad8-6c8c488697b6

This Presentation has an RSS Widget setup to display 211 characters, another placeholder setup to display 212 characters, and one final placeholder setup to show the full description. As you can see, only the widget setup for 211 characters is displaying content.

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Possible RSS Widget Issue](https://trello.com/c/DR8IVBD7/6216-1-possible-rss-widget-issue)

**Comment by sheadarlison** [comment]
@btfrise see this issue here: https://github.com/Rise-Vision/widget-rss/issues/83

**Comment by sheadarlison** [comment]
@btfrise this is still open, is it okay if I open this issue back up?

**Comment by btfrise** [comment]
@sheadarlison Yep

**Comment by stulees** [comment]
The fix has been deployed with #122 .

---

**Problem** 

- Horizontal scrolling content greater than the maximum allowed canvas width resulted in not displaying any content at all. 

**Solution** 

- Display/scroll the maximum canvas width of content and truncate the ending text with an ellipsis 

**How to validate** 

1. Add a Presentation with an RSS Widget placeholder
2. Set the presentation to the Scroll transition in the left direction
3. Add an RSS feed where most of the stories contain a lot of characters (https://www.nasa.gov/rss/dyn/breaking_news.rss)
4. Select show full description
5. Apply somewhat large font sizes to increase chance of content being longer than maximum canvas width.
