### ISSUE TITLE
Widget not showing images

### ISSUE THREAD

**Issue by rudibravo** [Rise-Vision/widget-rss#104]
**What's happening?**
On some feeds (at least one example) the images are not displaying correctly.

**How to recreate**
1. Created a RSS widget and used the url http://feeds.feedburner.com/foxnews/latest
2. Tried all layout options
3. The feed was not showing images (screenshot attached)

![got](https://user-images.githubusercontent.com/160045/32520650-d778d346-c3f7-11e7-9572-a4235799ecf6.png)

Expected images like this example RSS reader

![expected](https://user-images.githubusercontent.com/160045/32520683-033e2d00-c3f8-11e7-90d5-9831715585ee.png)

**Comment by rudibravo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 104: RSS widget not showing images.](https://trello.com/c/qYL6NDcW/6312-issue-104-rss-widget-not-showing-images)

**Comment by jungeunyoon** [comment]
@robb-price The fix should be entirely unrelated to what you're seeing. I'm also having trouble replicating the problem because the images are working for me. Could you possibly link me to the specific presentation so I could check that one out please? Thanks!

**Comment by robb-price** [comment]
@jungeunyoon Sure, you can use this Presentation https://apps.risevision.com/editor/workspace/4fb2e65b-1175-4ed1-9431-926383289baf/?cid=556323b8-984c-4127-aa08-4d73d019bcb8

Thanks!

**Comment by jungeunyoon** [comment]
@robb-price Yeah, it's still working for me. The only images that aren't displaying are the ones that don't have one. 

Might be pulling from a cached version of rss widget. Would you mind trying clearing your cache and let me know if the same problem occurs to rule that out?

**Comment by robb-price** [comment]
@jungeunyoon That was it. What a rookie mistake :) Thanks!
