### ISSUE TITLE
RSS Doesn't let images show full screen 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-rss#110]
### What is the expected behavior?
Image shows at 1920x1080 when placeholder is set to 1920x1080 and the image is naturally at 1920x1080.

### What is the actual behavior?
There is a border around the image and inline styles are being applied that are changing the size.

### What steps can be taken to replicate the problem?
Will attach all details with an example of the problem occurring to the card. 

https://help.risevision.com/hc/en-us/community/posts/360010735603

**Comment by jungeunyoon** [comment]
The fix has been deployed with #115.

---

**Problem** 

- There is a margin around images that doesn't allow them to be displayed on full screens.

**Solution** 

- Removed margins around images. 

**How to validate** 

1. Build a presentation to use full screen RSS Widget with only image.
2. Deploy presentation to screen.
