### ISSUE TITLE
RSS-Widget not working in android

### ISSUE THREAD

**Issue by woneal1983** [Rise-Vision/widget-rss#127]
Alan gave me a copy of the RSS feed so i can figure out the issue with it not running on Android. From what i can tell, there is something in the widget.js and jquery 2.2.0 that isn't working correctly. So here is what i have done. I downloaded the uncompressed version of 2.2.0 jquery and put it in the JS folder of the widget. http://scottsdigitalsignage.com/widget/RSS/1.0.0/dist/js/jquery.js
Then I ran the widget in a blank presentation. I get an error code on line 2404 in jquery stating length is undefined. From there, i tried to figure out why the widget was using that particular function that has line 2404. I couldn't find anything. It's hard to figure out and i was wondering If a developer could help work on this issue. 
Thanks
Scott

**Comment by sheadarlison** [comment]
Hi Scott, 

We don't support Android and we're focusing on improving our supported platforms so we don't have the resources to pursue investigating and fixing this issue right now, if that changes I'll let you know. 

Thanks,
Shea 

FYI @alanclayton
