### ISSUE TITLE
No Images for certain RSS feeds

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/widget-rss#128]
### What is the expected behavior?
Images show on an RSS feed

### What is the actual behavior?
Images do not show. Though they do show on the classic rss gadget

### What steps can be taken to replicate the problem?
Problem can be viewed in this presentation. Same RSS feed (feed validates) but image sonly show on the old rss feed:

https://apps.risevision.com/editor/workspace/7666c89f-9c3b-4785-89ec-bb932312f1a1/?cid=40920f96-9621-4cce-a46e-1b839e5c5688

**Comment by santiagonoguez** [comment]
Fixed in latest master branch
