### ISSUE TITLE
RSS Widget: Separator adds a trailing Separator

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/widget-rss#130]
### What is the expected behavior?
Setting a nonzero value for Separator adds a Separator the specified number of pixels in size in between RSS stories.

### What is the actual behavior?
Setting a nonzero value for Separator adds a Separator the specified number of pixels in size after every RSS story.

### What steps can be taken to replicate the problem?
1. Create a small placeholder in a presentation over a white background.
1. Run an RSS widget, I used this feed when testing. http://feeds.reuters.com/news/artsculture
1. Set Stories to 2 per page, some larger number (I used 10) in all.
1. Set Separator to some large value, like 50px.
1. You should see based on the change in color where the separator is that a separator is added after each story, rather than between the stories.

In particular, this causes weird behavior with image scaling. See the two linked presentations.

**Comment by stulees** [comment]
Fixed by #131 @PatrickA-RiseVision FYI
