### ISSUE TITLE
Increases in ETIMEDOUT and ESOCKETTIMEDOUT errors

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/widget-rss#133]
Details in this card: https://trello.com/c/acZ9WUQD/7112-investigate-low-reliability-on-rss-widget-1

**Comment by stulees** [comment]
@santiagonoguez As discussed, logs/stats are showing the VM memory upgrade and increase of request timeout from 10 to 30 seconds for feed parser have made the impact we were hoping for in reducing ETIMEDOUT errors. Along with the widget deployment today, pretty confident it will remain this way. Closing the issue, cheers.
