### ISSUE TITLE
Uptime errors not published to user

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-rss#151]
The following uptime errors are being reported, but they are not being published to the User:

- E000000058
- E000000059
- E000000061

**Comment by ezequielc** [comment]
@stulees @alanclayton  I don't see this error in our defects spreadsheet. Is this something we want to pursue? Thanks!

**Comment by stulees** [comment]
@ezequielc This has had a status of **blocked** in our defects spreadsheet, along with a few others. It's not clear to me if they should continue to be **blocked** or they should be closed. @alanclayton thoughts?

**Comment by alanclayton** [comment]
@ezequielc I think RSS should be open based on recent uptime analysis. As for other blocked defects, I will defer to you guys on if they should be open or closed. They were created a while ago and would close those that are no longer relevant. Thanks

**Comment by ezequielc** [comment]
@alanclayton For RSS, we already show the errors in the UI but we need to update the error messages. I have that tracked as an open action so I think we can close this. Let me know if ok with you. Thanks!

**Comment by alanclayton** [comment]
Sounds good @ezequielc

**Comment by ezequielc** [comment]
@stulees fyi, feel free to close this and update the spreadsheet. Thanks!
