### ISSUE TITLE
RSS does not load in RSS Widget

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-rss#32]
**How to recreate**
Add the RSS Widget (use the <a href="http://environmentaldashboard.org/events/feed/">user's link</a>) in the new Editor or RVA.  See <a href="https://apps.risevision.com/editor/workspace/1020aea9-a842-47ff-b3e3-2673f07635fc/?cid=960b72df-9af7-476b-8a47-b67ded4c779d">this presentation</a>.

**What happens**
'Please wait while your feed is loaded message'.
The RSS feed does not appear in the RSS Widget when added in the new Editor or in RVA.  This error appears in the Developer Console:

<img width="1416" alt="screen shot 2016-03-14 at 1 06 17 pm" src="https://cloud.githubusercontent.com/assets/5868781/13754316/e954112a-e9ec-11e5-9244-baf1d425c1a1.png">

**What should happen**
The RSS feed to appear.

**Notes**
The RSS appears when using the RSS Gadget.  To compare use <a href="http://rva.risevision.com/#/PRESENTATION_MANAGE/id=49d40256-9a8f-4b59-a910-b4900b8b5585?cid=960b72df-9af7-476b-8a47-b67ded4c779d">this presentation</a>.

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/hcs@risevision.com/conversations/4320183555

**Comment by alanclayton** [comment]
The feed url is not a valid RSS or Atom format. See here, https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fenvironmentaldashboard.org%2Fevents%2Ffeed%2F
