### ISSUE TITLE
Unvalidated Feed works with Gadget, but not Widget.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-rss#36]
<b>How it works now:</b>
1. Add this feed to the Widget: http://www.springfieldmo.gov/support/newsflash1.xml
2. Notice that there are no obvious errors in the logs, and the Widget images do not show.
3. Add the same feed to the Gadget, and notice that the images show.

<b>How it should work:</b>
Since the images show in the Gadget, they should show in the Widget.

**Comment by alanclayton** [comment]
Issue has been fixed.
