### ISSUE TITLE
Custom font not rendered when Widget configured for horizontal scrolling

### ISSUE THREAD

**Issue by stulees** [Rise-Vision/widget-rss#55]
**How to recreate**
- Configure the Widget to use horizontal scrolling by choosing "Scroll" from Transition setting and "Left" from Direction setting
- Apply a custom font to be used for Title, Description, Author, or Timestamp

**What happens**
The custom font is not rendered, a fallback font is applied instead

**What should happen**
The custom font is applied 

**Notes**
Custom font is applied correctly for any other Transition state

**Comment by donnapep** [comment]
This has been fixed by PR #57.
