### ISSUE TITLE
Unable to run the widget

### ISSUE THREAD

**Issue by skaluva** [Rise-Vision/widget-rss#6]
Hi,
When to try to run the widget using "widget preview" tool, i'm gettting javascript error preventing the "widget" to load. I'm able to load "settings.html" but none of layout files (layout-1x2.html etc.,) are getting loaded.
![image](https://cloud.githubusercontent.com/assets/2105229/8637626/8342ef0a-28b8-11e5-806e-9680d5fc13ca.png)

Please suggest.

**Comment by alanclayton** [comment]
@stulees @donnapep @rodrigopavezi is this still an issue?

**Comment by stulees** [comment]
@alanclayton Not an issue anymore, this was logged when the widget was a work in progress and only available from this repo.
