### ISSUE TITLE
Custom Layout Template

### ISSUE THREAD

**Issue by mcqueenaece** [Rise-Vision/widget-rss#63]
I'm trying to use a custom layout template.  I've copied one of the default templates to my web host and no matter what the placeholder gives the error 'The layout file could not be loaded'.    The layout file is hosted here: http://www-math.umd.edu/signage/MathDirRSSStyle.html

**Comment by btfrise** [comment]
@mcqueenaece Thanks for reporting this. Our developers have taken a look and determined the issue.

A current workaround would be to host your layout file on Rise Storage, or possibly another host.

**Comment by mcqueenaece** [comment]
I tried another host, but still not working.  I don't have Rise Storage.

**Comment by btfrise** [comment]
@mcqueenaece In order for this to work with your hosting, your server will need to apply CORs headers. You may look into implementing this on your web server, or utilizing a server that does apply CORs headers.
