### ISSUE TITLE
Page Transition ignores the "Show Each Item for" setting.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-rss#64]
<b>How it works now:</b>
1. Add the RSS Widget to your Presentation, use any RSS Feed, for example: http://rss.cnn.com/rss/edition.rss. 
2. Set the Transition to Page, and the "Show Each Item for" setting to 3 seconds.
3. Preview the Presentation, or play on a Display. Notice that the Widget shows for roughly 10 seconds before moving to the next item.

For further clarification: https://goo.gl/GiVtRw

<b>How it should work:</b>
Regardless of the transition, the item should show for the set duration in the "Show Each Item for" setting.

**Comment by alanclayton** [comment]
Issue has been corrected.
