### ISSUE TITLE
Request: center image horizontally in 16x9 layout

### ISSUE THREAD

**Issue by csshepard** [Rise-Vision/widget-rss#67]
Would it be possible to have the 16x9 layout center the image horizontally within the div? 
Thanks

**Comment by donnapep** [comment]
Hi @csshepard.

Have you considered using our [rise-rss](https://github.com/Rise-Vision/rise-rss) component? You can use it to retrieve feed data, and then build your own UI for displaying it.

**Comment by csshepard** [comment]
I'll look into that.  I'm trying to replace the old Photo Album gadget, specifically the slideshow.  I can probably use the rise-rss component to replicate that as a widget.
