### ISSUE TITLE
Summary of a feed is being used instead of the description

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-rss#75]
<b>How it works now:</b>
Using <a href="https://apps.risevision.com/editor/workspace/9d50f812-69c2-4252-9c7e-2889edfcc5f8/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a>, notice that the <b>summary</b> value of their feed is being used instead of <b>description</b>, however the items from our parser passed to our component contain "description" properties.

**Comment by donnapep** [comment]
Running the feed through the validator, it complains about an "Undefined item element: summary". RSS feeds shouldn't have a summary element. Atoms feeds have those though, and I believe that is what is causing the parser to return the summary in the description field and vice versa.

In other words, the feed needs to pass the validation. If it passes and there's still an issue, then we could investigate further.
