### ISSUE TITLE
RSS Widget show &amp instead of just &

### ISSUE THREAD

**Issue by joelasso** [Rise-Vision/widget-rss#80]
<b>How it works now:</b>
The RSS feed http://feeds.bbci.co.uk/news/rss.xml is showing "&amp" instead of "&" on the news that contain that character. Right now the 3rd news entry on the RSS has that symbol.

<b>How it should work:</b>
It should just display "&" instead of "&amp"

Intercom Conversation: 
https://app.intercom.io/a/apps/d85f4ah4/inbox/mentions/conversations/7805298067

Affected presentation:
https://apps.risevision.com/editor/workspace/160d0998-3138-40f9-9cce-8c42c9c1321f/?cid=ed509810-5803-4187-ab52-04c5f67b55dc

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 80: RSS shows "&amp" instead of "&"](https://trello.com/c/2BtISYZN/3030-1-issue-80-rss-shows-amp-instead-of)

**Comment by alanclayton** [comment]
Issue fixed.
