### ISSUE TITLE
Valid RSS Feed is Showing an Error

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-rss#85]
###Currently Happening
This RSS feed (https://www.wired.com/feed) passes the W3C validation (https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.wired.com%2Ffeed) but shows "The URL provided is not an RSS feed in the widget" and "Sorry, there was a problem with the RSS feed" in Preview. 

###What Should Happen
The feed works as expected, no errors are shown. 

Note: Once I made a copy of the Widget it started showing again.

**Comment by rodrigopavezi** [comment]
https://github.com/Rise-Vision/feed-parser/pull/18
