### ISSUE TITLE
Font sizes are in PT no option for PX

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-rss#87]
###Notes: 
https://apps.risevision.com/editor/workspace/2e892487-e1eb-4ee7-8005-bf26ab6519a4/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

https://www.screencast.com/t/ItzIFz8oGG

Let me know if you need anything else. 

Thanks

**Comment by alanclayton** [comment]
Fix released with #88
