### ISSUE TITLE
Incorrect message displayed when feed has no items

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-rss#90]
<b>How it works now</b>
Using <a href="http://www.upenn.edu/calendar-export/?type=rss2&showndays=0&school=40">this RSS Feed</a>, notice that the Widget sits on ""please wait while your feed is loaded" instead of saying the feed is empty and moving to the next item in the Playlist.

<b>How it should work</b>
Since this is an empty feed, it should state that, and move to the next Playlist item.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 90: Incorrect message displayed when feed has no items](https://trello.com/c/ns73X639/4613-1-issue-90-incorrect-message-displayed-when-feed-has-no-items)

**Comment by stulees** [comment]
@robb-price Fixed with this PR https://github.com/Rise-Vision/feed-parser/pull/19 , closing, thanks.
