### ISSUE TITLE
No way to hide the description in the RSS Widget

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-rss#96]
If you set the number of characters to show in the description snippet to 0 and save, the Widget ignores the setting and shows 120 characters. And there is no other way to hide the description and only show the title. 

https://www.screencast.com/t/g4PcoWmg

**Comment by alanclayton** [comment]
@sheadarlison I think this is a feature request more so than a defect right. The widget doesn't support not showing the description. 

Would using the component be an option https://github.com/Rise-Vision/rise-rss?

**Comment by sheadarlison** [comment]
@alanclayton Kind of both, I'd like a feature to hide description, but at the same time if you say the description should be 0 characters shouldn't it be 0 characters? 

The component is an option but impractical for small projects where we can't invest dev time and use Wigdets.

Thanks

**Comment by rodrigopavezi** [comment]
@sheadarlison this should be fixed now with release of https://github.com/Rise-Vision/widget-rss/pull/98. cheers
