### ISSUE TITLE
RSS Widget parses HTML in the description tag but not the content tag

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-rss#99]
<b>How it works now</b>
As mentioned in <a href="https://community.risevision.com/rise_vision_inc/topics/why-does-the-rss-widget-parse-html-in-the-tag-but-not-the-tag">this forum discussion</a>, notice that feeds that have a description tag that have a short preview are ignored in favor of the <content> tag. But when using the <content> tag for the feed content, the HTML is not parsed by the RSS widget causing issues with line breaks and other formatting issues. The HTML contents of the <content> tag should be parsed the same as the <description> tag is in the news feed.

Feeds to test with: 
"News" feed that has content in <description> tag: https://www.jdsalaw.com/news/?format=rss

"Seminars" feed that has content in <content encoded> tag: https://www.jdsalaw.com/seminars/?format=rss

**Comment by alanclayton** [comment]
Unable to replicate. Closing issue.
